// Import from node_modules
import Head from 'next/head';
// import { useLayoutEffect , useRef  } from 'react';
/* import { gsap } from 'gsap';
import { ScrollTrigger } from 'gsap/dist/ScrollTrigger';
import { ScrollSmoother } from 'gsap/dist/ScrollSmoother'; */

// Components
import Line from 'src/components/tokens/Line';
import Separator from 'src/components/tokens/Separator';
import Features from '../components/sections/Features';
import Hero from '../components/sections/Hero';
import Last from '../components/sections/Last';
import Partners from '../components/sections/Partners';
import Social from '../components/sections/Social';
import Story from '../components/sections/Story';
import Team from '../components/sections/Team';

/* gsap.registerPlugin(ScrollTrigger, ScrollSmoother) */

export default function Home() {
/* 	const main = useRef();
	const smoother = useRef();

	useLayoutEffect(()=> {
		// create smooth scrolling
		smoother.current = ScrollSmoother.create({
			smooth: 2, // seconds it takes to catch up to native scroll position
			effects: true, // look for data-speed and data-lag attributes on elements ana animate accordingly
		});
		ScrollTrigger.create({
			trigger: '.gsap__team',
			pin: true,
			star: 'center center',
			end: '+=300',
			markers: true,
		});
	}, []); */

	return (
		<>
			<Head>
				<title>A&S Lifts</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
			</Head>
			{/* add ref={main} inside main element */}
			<main>
				{/* Hero section */}
				<Hero
				className="gsap__hero"
					dataSpeed="0.5"
				 />

				{/* Partners section */}
				<Partners />

				{/* Separator */}
				<Separator />

				{/* Features section */}
				<Features
				className="gsap__features"
					dataSpeed="0.8"
				 />

				{/* Separator */}
				<Separator />

				{/* Social section */}
				<Social />

				{/* Story section */}
				<Story />

				{/* Team section */}
				<Team
					className="gsap__team"
					dataSpeed="1.5"
				/>

				{/* Last action section */}
				<Last />

				{/* Line on the top of the footer */}
				<Line />
			</main>
		</>
	);
}
