// Import from node_modules
import Head from 'next/head';

// Components
import Hero from '@/components/sections/Hero';
import Partners from '@/components/sections/Partners';
import Features from '@/components/sections/Features';
import Social from '@/components/sections/Social';
import Story from '@/components/sections/Story';
import Team from '@/components/sections/Team';
import Last from '@/components/sections/Last';

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main>
				{/* Hero section */}
				<Hero />

				{/* Partners section */}
				<Partners />

				{/* Features section */}
				<Features />

				{/* Social section */}
				<Social />

				{/* Story section */}
				<Story />

				{/* Team section */}
				<Team />

				{/* Last action section */}
				<Last />
			</main>
		</>
	);
}
