// Import from node_modules
import Head from 'next/head';

// Components
import Line from 'src/components/tokens/Line';
import Separator from 'src/components/tokens/Separator';
import Features from '../components/sections/Features';
import Hero from '../components/sections/Hero';
import Last from '../components/sections/Last';
import Partners from '../components/sections/Partners';
import Social from '../components/sections/Social';
import Story from '../components/sections/Story';
import Team from '../components/sections/Team';

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main>
				{/* Hero section */}
				<Hero />

				{/* Partners section */}
				<Partners />

				{/* Separator */}
				<Separator />

				{/* Features section */}
				<Features />

				{/* Separator */}
				<Separator />

				{/* Social section */}
				<Social />

				{/* Story section */}
				<Story />

				{/* Team section */}
				<Team />

				{/* Last action section */}
				<Last />

				{/* Line on the top of the footer */}
				<Line />
			</main>
		</>
	);
}
